import Head from "next/head";

import axios from "axios";
import { ResultType, SearchType } from "../types";
import { useState } from "react";

const Home = () => {
  const [isTyping, setIsTyping] = useState(false);
  const [searchResults, setSearchResults] = useState<ResultType[]>([]);
  const onChangeHandler: React.ChangeEventHandler<HTMLInputElement> = async (
    e
  ) => {
    const input = e.currentTarget;
    const searchTerm = input.value;
    const URI = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/search/${searchTerm}`;
    try {
      const res = await axios.get(URI);
      const data = res.data as SearchType;
      setSearchResults(data.results);
    } catch (err) {
      console.log(err);
    }
  };
  const onSubmitHandler: React.FormEventHandler<HTMLFormElement> = async (
    e
  ) => {
    e.preventDefault();
    const form = e.currentTarget;
    const searchTerm = form.search.value;
    const URI = `${process.env.NEXT_PUBLIC_API_ENDPOINT}/search/${searchTerm}`;
    try {
      const res = await axios.get(URI);
      const data = res.data as SearchType;
      setSearchResults(data.results);
    } catch (err) {
      console.log(err);
    }
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <form onSubmit={(e) => onSubmitHandler(e)}>
        <label htmlFor="search"></label>
        <input
          type="text"
          id="search"
          name="search"
          onChange={(e) => onChangeHandler(e)}
        />
        <input type="submit" value="Search" />
      </form>
      <div>
        {searchResults.map((result) => {
          const { id, overview, name, poster_path } = result;

          return (
            <div key={id}>
              <h2>
                <a href={`/show/${id}`}>{name}</a>
              </h2>
              {poster_path && (
                <img
                  src={`https://image.tmdb.org/t/p/w500${poster_path}`}
                  alt=""
                />
              )}
              <p>{overview}</p>
            </div>
          );
        })}
      </div>
    </div>
  );
};

export default Home;
