import Head from "next/head";
import SearchForm from "../components/SearchForm";

const Home = () => {
  return (
    <main>
      <Head>
        <title>IMDb TV Show Graph</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          property="og:title"
          content="Career Portfolio - Mitchell Victoriano"
        />
        <meta
          property="og:image"
          content="https://mitchellvictoriano.com/images/thumbnail.png"
        />
        <meta
          property="og:description"
          content="Welcome to the career portfolio for Mitchell Victoriano. Here you can learn more about Mitchell and his experiences, view mechanical and computer science projects that he has been a part of, and get in contact with him for work or to discuss anything."
        />
        <meta property="og:url" content="https://mitchellvictoriano.com/" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />

        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="favicon-16x16.png"
        />
        <link rel="manifest" href="site.webmanifest" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <h1 className="home__header">Search for a TV Show to Explore</h1>
      <SearchForm />
    </main>
  );
};

export default Home;
