import Head from "next/head";
import SearchForm from "../components/SearchForm";

const Home = () => {
  return (
    <main>
      <Head>
        <title>IMDb TV Show Graph</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        ></link>
      </Head>
      <h1 className="home__header">Search for a TV Show to Explore</h1>
      <SearchForm />
    </main>
  );
};

export default Home;
